//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public bool Gender { get; set; }
        public bool Married { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string BirthPlace { get; set; }
        public string PersonId { get; set; }
        public string TakenPIPlace { get; set; }
        public Nullable<System.DateTime> TakenPIDate { get; set; }
        public string Address { get; set; }
        public string NativeLand { get; set; }
        public string Tabernacle { get; set; }
        public string BankId { get; set; }
        public string Bank { get; set; }
        public byte[] Image { get; set; }
        public string Mobie { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Income { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public Nullable<int> Nationnality_Id { get; set; }
        public Nullable<int> Job_Id { get; set; }
        public Nullable<int> Folk_Id { get; set; }
        public int CreatedByEmployeeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastEditedByEmployeeId { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee CreatedByEmployee { get; set; }
        public virtual Employee LastEditedByEmployee { get; set; }
        public virtual Folk Folk { get; set; }
        public virtual Job Job { get; set; }
        public virtual Nationnality Nationnality { get; set; }
        public virtual Religion Religion { get; set; }
    }
}
