//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.CreatedCustomers = new HashSet<Customer>();
            this.LastEditedCustomers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public bool Gender { get; set; }
        public bool Married { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string BirthPlace { get; set; }
        public string PersonId { get; set; }
        public string TakenPIPlace { get; set; }
        public Nullable<System.DateTime> TakenPIDate { get; set; }
        public string Address { get; set; }
        public string NativeLand { get; set; }
        public string Tabernacle { get; set; }
        public string BankId { get; set; }
        public string Bank { get; set; }
        public byte[] Image { get; set; }
        public string Mobie { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PublicId { get; set; }
        public int BaseSalary { get; set; }
        public Nullable<double> FactorySalary { get; set; }
        public Nullable<int> AllowedSalary { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public string LaborId { get; set; }
        public Nullable<System.DateTime> LaborDay { get; set; }
        public string LaborPlace { get; set; }
        public string Password { get; set; }
        public Nullable<int> Computing_Id { get; set; }
        public int Deparmant_Id { get; set; }
        public Nullable<int> ForeignLanguage_Id { get; set; }
        public Nullable<int> Learning_Id { get; set; }
        public int Position_Id { get; set; }
        public int TypeStaff_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public Nullable<int> Nationnality_Id { get; set; }
        public Nullable<int> Job_Id { get; set; }
        public Nullable<int> Folk_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual Computing Computing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> CreatedCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> LastEditedCustomers { get; set; }
        public virtual Deparmant Deparmant { get; set; }
        public virtual ForeignLanguage ForeignLanguage { get; set; }
        public virtual Learning Learning { get; set; }
        public virtual Position Position { get; set; }
        public virtual Folk Folk { get; set; }
        public virtual Job Job { get; set; }
        public virtual Nationnality Nationnality { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual TypeStaff TypeStaff { get; set; }
    }
}
